#!/bin/bash

ROOT_DIR="$1"
DEPLOY_DIR="$2"
BINARY_DIR="$ROOT_DIR/bin"
SCRIPTS_DIR="$ROOT_DIR/scripts"
IMAGES_DIR="$ROOT_DIR/docs/images"
WIN_DEPLOY_DIR="$DEPLOY_DIR/coreutils-win"
LINUX_DEPLOY_DIR="$DEPLOY_DIR/coreutils-linux"

echo "##### Deploy for Windows SO... #####"
echo ">>> Create dirs..."
mkdir -p "$WIN_DEPLOY_DIR"
mkdir -p "$WIN_DEPLOY_DIR/scripts"
mkdir -p "$WIN_DEPLOY_DIR/bin"
mkdir -p "$WIN_DEPLOY_DIR/installers"

echo ">>> Move/Copy files and dirs..."
cp -r "$BINARY_DIR/windows/." "$WIN_DEPLOY_DIR/bin"
cp -r "$SCRIPTS_DIR/apps" "$WIN_DEPLOY_DIR/scripts/"
cp -r "$SCRIPTS_DIR/cmd" "$WIN_DEPLOY_DIR/scripts/"
cp -r "$SCRIPTS_DIR/libs" "$WIN_DEPLOY_DIR/scripts/"
cp -r "$SCRIPTS_DIR/profiles" "$WIN_DEPLOY_DIR/scripts/"
cp -r "$IMAGES_DIR" "$WIN_DEPLOY_DIR/images"
cp "$SCRIPTS_DIR/installer-and-others/start.bat" "$WIN_DEPLOY_DIR/"
mv "$WIN_DEPLOY_DIR/bin/install.exe" "$WIN_DEPLOY_DIR/installers/"
mv "$WIN_DEPLOY_DIR/bin/uninstall.exe" "$WIN_DEPLOY_DIR/installers/"


echo "##### Generate for Linux SO... #####"
echo ">>> Create dirs..."
mkdir -p "$LINUX_DEPLOY_DIR"
mkdir -p "$LINUX_DEPLOY_DIR/scripts"
mkdir -p "$LINUX_DEPLOY_DIR/bin"
mkdir -p "$LINUX_DEPLOY_DIR/installers"

echo ">>> Move/Copy files and dirs..."
cp -r "$BINARY_DIR/linux/." "$LINUX_DEPLOY_DIR/bin"
cp -r "$SCRIPTS_DIR/apps" "$LINUX_DEPLOY_DIR/scripts/"
cp -r "$SCRIPTS_DIR/cmd" "$LINUX_DEPLOY_DIR/scripts/"
cp -r "$SCRIPTS_DIR/libs" "$LINUX_DEPLOY_DIR/scripts/"
cp -r "$SCRIPTS_DIR/profiles" "$LINUX_DEPLOY_DIR/scripts/"
cp -r "$IMAGES_DIR" "$LINUX_DEPLOY_DIR/images"
cp "$SCRIPTS_DIR/installer-and-others/start.sh" "$LINUX_DEPLOY_DIR/"
mv "$LINUX_DEPLOY_DIR/bin/install" "$LINUX_DEPLOY_DIR/installers/"
mv "$LINUX_DEPLOY_DIR/bin/uninstall" "$LINUX_DEPLOY_DIR/installers/"
